services:
##  zookeeper:
##    image: bitnami/zookeeper:latest
##    container_name: zookeeper
##    ports:
##      - "2181:2181"
###    environment:
###      ALLOW_ANONYMOUS_LOGIN: "yes"
##    networks:
#      - realtime-chat-network
#
##  kafka:
##    image: bitnami/kafka:latest
##    container_name: kafka
##    ports:
##      - "9092:9092"
##    environment:
##      KAFKA_BROKER_ID: 1
##      KAFKA_LISTENERS: PLAINTEXT://:9092
##      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
##      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
##    networks:
##      - realtime-chat-network
##    depends_on:
##      - zookeeper
#
  app:
    image: kyoo0115/realtimechatapplication:latest
    container_name: app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://database-1.cbyskwqq6s69.ap-northeast-2.rds.amazonaws.com:3306/chatapp-aws
      SPRING_DATASOURCE_USERNAME: kyoomin1
      SPRING_DATASOURCE_PASSWORD: kyoominlee1
#      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
#    depends_on:
#      - kafka
    networks:
      - realtime-chat-network

networks:
  realtime-chat-network:
    external: true
