version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://${DOCKER_HOST_IP:-localhost}:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  app:
    image: kyoo0115/realtimechatapplication:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://realtime-chat.cbyskwqq6s69.ap-northeast-2.rds.amazonaws.com:3306/realtime-chat
      SPRING_DATASOURCE_USERNAME: kyoomin1
      SPRING_DATASOURCE_PASSWORD: kyoominlee1
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka

networks:
  default:
    external:
      name: realtime-chat-network
