version: '3.8'

services:
  app:
    image: kyoo0115/realtimechatapplication:latest
    container_name: app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://database-1.cbyskwqq6s69.ap-northeast-2.rds.amazonaws.com:3306/chatapp-aws
      SPRING_DATASOURCE_USERNAME: kyoomin1
      SPRING_DATASOURCE_PASSWORD: kyoominlee1
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: kyoominmir41@gmail.com
      SPRING_MAIL_PASSWORD: aekh ytcs gyig uldg
      SPRING_ELASTICSEARCH_REST_URIS: http://elasticsearch:9200
    networks:
      - realtime-chat-network
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - realtime-chat-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.2
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - realtime-chat-network

networks:
  realtime-chat-network:
    external: true
