spring:
  profiles:
    active: prod
  application:
    name: realtime-chat-application
  jpa:
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: true
    show-sql: true
  jwt:
    secret: ZGF5b25lLXNwcmluZy1ib290LWRpdmlkZW5kLXByb2plY3QtdHV0b3JpYWwtand0LXNlY3JldC1rZXkK
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 9b0ff9395d3346c83412725ba424f35d
            client-secret: aWOlyeAGkiF7enMgoJA7HIpxEF8OBmNN
            redirect-uri: http://localhost:8080/oauth2/callback/{registrationId}
            authorization-grant-type: authorization_code
            scope: profile_nickname
            client-authentication-method: client_secret_post

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
logging:
  level:
    org.springframework.security: DEBUG
    project.realtimechatapplication: DEBUG
    org.springframework.web.socket.messaging: TRACE
