spring:
  profiles:
    active: prod
  application:
    name: realtime-chat-application
  jpa:
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: true
    show-sql: true
  jwt:
    secret: ZGF5b25lLXNwcmluZy1ib290LWRpdmlkZW5kLXByb2plY3QtdHV0b3JpYWwtand0LXNlY3JldC1rZXkK