spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://realtime-chat.cbyskwqq6s69.ap-northeast-2.rds.amazonaws.com:3306/realtime-chat
    username: kyoomin1
    password: kyoominlee1

  mail:
    host: smtp.gmail.com
    port: 587
    username: kyoominmir41@gmail.com
    password: aekh ytcs gyig uldg
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true