spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://database-1.cbyskwqq6s69.ap-northeast-2.rds.amazonaws.com:3306/chatapp-aws
    username: kyoomin1
    password: kyoominlee1

  mail:
    host: smtp.gmail.com
    port: 587
    username: kyoominmir41@gmail.com
    password: aekhytcsgyiguldg
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
  data:
    elasticsearch:
      client:
        reactive:
          endpoints: http://elasticsearch:9200